### ISSUE TITLE
Missing prefix-entries after initializing repository

### ISSUE THREAD

**Issue by raphzack** [jakobehn/GitFlow.VS#35] opened 2016-01-21 12:14 UTC
After cloning my repo (bitbucket) and initializing it using the extension with all the defaults from the 'initialize-view', I am not able to start a hotfix or feature. I get the error: Fatal: Version tag not set. Please run 'git flow init'.

As far as I know you run a 'git flow init -f' command in the background and feed the StandardInput with the entered prefixes. That command should write some entries into the git-config-file but my config file only has only the following entry in the prefix-section:
[gitflow "prefix"]
feature = feature/

For some reason the command terminates before all the prefixes are written.

**Comment by eloekset** [comment] 2016-01-22 16:47
I've also got this error message now using the GitFlow plugin in Visual Studio. I can see from the GitFlow.VS log that the following command was executed on initialize:

```
Running git flow init -f

Which branch should be used for bringing forth production releases?
   - master
Branch name for production releases: [master]
 Branch name for "next release" development: [develop]
 
How to name your supporting branch prefixes?
Feature branches? [feature/]
```

My config files looks like this after running the init command:
```
[core]
	bare = false
	filemode = false
	symlinks = false
	ignorecase = true
	logallrefupdates = true
[core]
	repositoryformatversion = 0
[remote "origin"]
	url = https://<account-name>.visualstudio.com/DefaultCollection/Playground/_git/<repo-name>
[remote "origin"]
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin
[branch "master"]
	merge = refs/heads/master
[gitflow "branch"]
	master = master
	develop = develop
[gitflow "prefix"]
	feature = feature/
[branch "develop"]
	remote = origin
[branch "develop"]
	merge = refs/heads/develop
```

A config file for another repo that has successfully created a release looks almost identical, except the develop branch is missing that the release branch is there:
```
[core]
	bare = false
	filemode = false
	symlinks = false
	ignorecase = true
	logallrefupdates = true
[core]
	repositoryformatversion = 0
[remote "origin"]
	url = https://<account-name>.visualstudio.com/DefaultCollection/Playground/_git/<repo-name>
[remote "origin"]
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin
[branch "master"]
	merge = refs/heads/master
[gitflow "branch"]
	master = master
	develop = develop
[gitflow "prefix"]
	feature = feature/
[branch "release/1.2"]
	remote = origin
[branch "release/1.2"]
	merge = refs/heads/release/1.2
```

**Comment by jakobehn** [comment] 2016-02-14 20:43
Thanks for reporting. This problem was caused by the extension not being compatible with the gitflow-avh version 1.9.1 that is now shipped with Git for Windows. I have updated the gitflow version and also fixed the problem.

**Comment by jakobehn** [comment] 2016-02-17 18:34
Marking this as closed

**Closed by jakobehn** 2016-02-17 18:34 UTC
