### ISSUE TITLE
GitFlow binaries not detected in 64 bit directory

### ISSUE THREAD

**Issue by wakers01** [jakobehn/GitFlow.VS#36] opened 2016-01-23 20:40 UTC
I was having trouble with the plugin detecting my existing install of GitFlow. After installing the plugin I would get the message "It looks like you don't have GitFlow installed. Let me do that for you." This was wrong, as I have GitFlow installed already, and clicking the "Install" button resulted in errors that I could see were happening in the Powershell script it runs, but the window disappeared too quickly for me to actually read the errors.

After tinkering for a while I found that, if I copied my whole Git directory from *C:\Program Files\Git* to *C:\Program Files (x86)\Git* the extension would detect the GitFlow binaries there and work as expected. I would assume that it would look at my Path variable to determine my Git directory, which is currently set to "%ProgramFiles%\Git\Cmd", but it only seems to want to look in Program Files (x86) for some reason.

I have cataloged all of this in the Q and A section of the Visual Studio Gallery page already, but I wanted to post my issue here as well.

**Comment by jakobehn** [comment] 2016-01-23 20:52
Thank for posting this. Actually, the code checks several different items, including the path so it is strange that it didn't find the correct path for your installation (see https://github.com/jakobehn/GitFlow.VS/blob/master/GitFlow.VS/GitHelper.cs) 

I need to add some more checks in that code, I have another issue posted as well on a similar problem

**Comment by thebooleanfrog** [comment] 2016-02-04 20:09
Hi. Had the same issue just now. Assuming the git install hasn't setup environment variables and modified the registry, the problem is that `Environment.GetFolderPath(Environment.SpecialFolder.ProgramFiles)` will return "C:\Program Files (x86)" on a 64-bit machine when running a 32-bit app (which presumably is the case for the vs extension). You could add this check to fix the problem:
`	if (Environment.Is64BitOperatingSystem)
	{
		var pfd = Microsoft.Win32.RegistryKey.OpenBaseKey(
			Microsoft.Win32.RegistryHive.LocalMachine, Microsoft.Win32.RegistryView.Registry64)
			.OpenSubKey(@"SOFTWARE\Microsoft\Windows\CurrentVersion").GetValue("ProgramFilesDir") as string;
		if (pfd != null)
		{
			gitPath = Path.Combine(pfd, "git");
			if (Directory.Exists(gitPath))
				return gitPath.TrimEnd('\\');
		}
	} `

...but my preferred option would be to be able to select the directory where git is installed :)

In the meantime I created a symlink between "C:\Program Files\Git" and "C:\Program Files (x86)\Git" to allow me to init my gitflow. Love the vs extension. Thanks.

**Comment by Pitterling** [comment] 2016-02-14 14:28
There is already an issue open - #23. I still believe the problem is, that your are running within VS, which is still a 32bit application. check my last comment.

**Comment by jakobehn** [comment] 2016-02-14 20:42
This issues should be fixed with the latest version (1.0.3.0) that I just uploaded. I now check the reg key  that is created with msysgit 2.6.1+

**Closed by jakobehn** 2016-02-14 20:42 UTC

**Comment by cfeilen** [comment] 2016-03-24 08:03
Not sure if this should be a new issue or not.
I just installed V1.1.0.0 (per the extensions window's version of GitFlow for VS 2015), and ran into the same problem, unable to find git on this machine.
I have the x64 version of git installed into c:\Program Files\Git.
HKEY_LOCAL_MACHINE\SOFTWARE\GitForWindows has the install path, but this is the 64bit regkey.

Your check for Environment.SpecialFolder.ProgramFiles seems to always return the (x86) folder.  (Is this compiled explicitly for 32bit, rather than AnyCPU?)

I'll get you a PR with a coded fix in a bit.

**Comment by wakers01** [comment] 2016-06-09 14:52
This seems to have become a problem again. The extension is not detecting the gitflow binaries even though they are installed. I can use the gitflow commands from powershell, but the extension still thinks gitflow isn't installed. My previous fix no longer works. Are there logs I can look at or troubleshooting steps I can take?

**Comment by Jojoshua** [comment] 2020-06-14 00:28
I just got this as well. Using the latest version of visual studio and the extension. Is there a workaround?
