### ISSUE TITLE
Visual Studio Tools for Apache and now extension not finding Gitflow

### ISSUE THREAD

**Issue by trendoid** [jakobehn/GitFlow.VS#45] opened 2016-03-10 01:27 UTC
I have Gitflow installed.  It works fine via command line.  But with the latest Visual Studio Tools for Apache Cordova the GitFlow Extension doesn't work anymore.

**Comment by jakobehn** [comment] 2016-03-10 08:00
Thanks for the report. Do you have any more information, any errors in the UI or in the outut window?

**Comment by trendoid** [comment] 2016-03-10 17:12
The powershell script that runs says that "GitFlow already installed" and closes.. it happens really fast.  I ran it manually and it does the same thing.

**Comment by jakobehn** [comment] 2016-03-13 12:15
I have installed the latest version (Update 7) of the VS Cordova Tools  on two different machines, but I can't reproduce any error

**Comment by jakobehn** [comment] 2017-01-07 08:51
Closing this one since I can't reproduce it

**Closed by jakobehn** 2017-01-07 08:51 UTC
